from __future__ import annotations
from typing import Protocol,Any
from ..models import Frame,WindowInfo,Element,ScreenState
class CaptureProvider(Protocol):
 def grab(self,target:str='desktop',monitor:int=0,window:int|None=None)->Frame: ...
 def close(self)->None: ...
class WindowProvider(Protocol):
 def active(self)->WindowInfo: ...
 def list(self)->list[WindowInfo]: ...
 def focus(self,hwnd:int)->bool: ...
class InputProvider(Protocol):
 def move(self,x:int,y:int,duration:float=0)->None: ...
 def click(self,x:int,y:int,button:str='left',count:int=1)->None: ...
 def drag(self,x1:int,y1:int,x2:int,y2:int,duration:float=.3,button:str='left')->None: ...
 def scroll(self,amount:int,x:int|None=None,y:int|None=None)->None: ...
 def key_down(self,key:str)->None: ...
 def key_up(self,key:str)->None: ...
 def type_text(self,text:str,interval:float=0)->None: ...
 def release_all(self)->None: ...
class PerceptionProvider(Protocol):
 def analyze(self,frame:Frame,window:WindowInfo)->tuple[list[Element],list[dict],list[dict]]: ...
class PlannerProvider(Protocol):
 def next_action(self,goal:str,state:ScreenState,history:list[dict])->dict[str,Any]: ...
