#!/usr/bin/env python3
"""Generate MANIFEST.md, docs/CAPABILITIES.md and top-level INDEX.md from the
repo and registry. Run: python scripts/generate_docs.py"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def tree_lines(d, prefix=""):
    out = []
    entries = sorted(p for p in d.iterdir()
                     if p.name not in (".git", "__pycache__", ".pytest_cache"))
    for i, p in enumerate(entries):
        last = i == len(entries) - 1
        conn = "\u2514\u2500\u2500 " if last else "\u251c\u2500\u2500 "
        size = "" if p.is_dir() else "  (%d B)" % p.stat().st_size
        out.append(prefix + conn + p.name + size)
        if p.is_dir():
            out += tree_lines(p, prefix + ("    " if last else "\u2502   "))
    return out


def make_manifest():
    lines = ["# Manifest", "",
             "Complete inventory of the Universal PDF Management & Creation "
             "Skill Repository (auto-generated by scripts/generate_docs.py).",
             "", "```"]
    lines += tree_lines(ROOT)
    lines += ["```", ""]
    skills = len([p for p in (ROOT / "skills").iterdir() if p.is_dir()])
    py = sum(1 for p in ROOT.rglob("*.py") if "__pycache__" not in str(p))
    md = sum(1 for p in ROOT.rglob("*.md"))
    lines += ["## Summary", f"- Skills (SKILL.md docs): {skills}",
              f"- Python modules: {py}", f"- Markdown documents: {md}"]
    (ROOT / "MANIFEST.md").write_text("\n".join(lines))


def make_capabilities():
    skills = json.loads((ROOT / "registry/skills.json").read_text())["skills"]
    L = ["# Capabilities Matrix", "",
         "Every skill, its category, its real engine module, preferred tool, "
         "validation and supported operations. Generated from "
         "registry/skills.json.", "", ""]
    L += ["| Skill | Category | Engine module | Preferred tool | Validation |",
          "|---|---|---|---|---|"]
    for s in skills:
        L.append("| `%s` | %s | %s | %s | %s |" % (
            s["slug"], s["category"], s["engine"].split(":")[0],
            s["preferred_tool"], s["validation"]))
    L.append("")
    for s in skills:
        L.append("\n### `%s`\n" % s["slug"])
        L += ["- " + o for o in s["operations"]]
    (ROOT / "docs/CAPABILITIES.md").write_text("\n".join(L))


def make_index():
    L = ["# Universal PDF System — Index", "",
         "Master navigation. Read in this order for the fastest path to "
         "understanding.",
         "",
         "## 1. Orientation",
         "- [README.md](README.md) — what this is and a quick start",
         "- [MANIFEST.md](MANIFEST.md) — complete file inventory",
         "",
         "## 2. Architecture & design",
         "- [ARCHITECTURE.md](ARCHITECTURE.md) — layers, routing, dependency graph",
         "- [docs/DESIGN-NOTES.md](docs/DESIGN-NOTES.md) — scale/weak-model/state/recovery",
         "- [DEPENDENCIES.md](DEPENDENCIES.md) — libraries, optional engines",
         "- [LIMITATIONS.md](LIMITATIONS.md) — honest limits & degradation map",
         "",
         "## 3. Skills",
         "- [skills/INDEX.md](skills/INDEX.md) — all 47 skills",
         "- [skills/UNIVERSAL_PDF.md](skills/UNIVERSAL_PDF.md) — master orchestrator skill",
         "- [docs/CAPABILITIES.md](docs/CAPABILITIES.md) — capability matrix",
         "- [registry/dependency-graph.json](registry/dependency-graph.json) — machine-readable graph",
         "",
         "## 4. Using it",
         "- [docs/INSTALL.md](docs/INSTALL.md) — install & import",
         "- [docs/USAGE.md](docs/USAGE.md) — individual & system mode",
         "- [workflows/](workflows/) — reusable end-to-end workflows",
         "- [examples/](examples/) — runnable examples",
         "- [templates/](templates/) — document / content templates",
         "",
         "## 5. Tests",
         "- [tests/](tests/) — pytest suite (skills + orchestration + large-doc)",
         "- Run: `python -m pytest tests/ -q`",
         "",
         "## 6. Developer",
         "- [scripts/generate_skills.py](scripts/generate_skills.py) — regenerate skills/registry",
         "- [scripts/generate_docs.py](scripts/generate_docs.py) — regenerate this + manifest",
         "- [registry/config.json](registry/config.json) — runtime configuration",
         ]
    (ROOT / "INDEX.md").write_text("\n".join(L))


if __name__ == "__main__":
    make_manifest()
    make_capabilities()
    make_index()
    print("docs regenerated")
