from __future__ import annotations
from typing import Protocol
class ComputerControlProvider(Protocol):
 def observe(self,scope:dict)->dict:...
 def inspect(self,query:dict)->dict:...
 def focus(self,target:dict)->dict:...
 def launch(self,app:dict)->dict:...
 def input(self,action:dict)->dict:...
 def wait(self,predicate:dict,timeout:float)->dict:...
 def verify(self,predicate:dict)->dict:...
 def cancel(self)->dict:...
 def stop(self)->dict:...
class EnvironmentAdapter(Protocol):
 name:str
 def capabilities(self)->dict:...
 def observe(self)->list[dict]:...
class VoiceProvider(Protocol):
 def listen(self,cancel)->dict:...
 def speak(self,text:str,state:dict)->dict:...
class GameAdapter(Protocol):
 game_id:str
 def permission_status(self)->dict:...
 def observe(self)->dict:...
 def skills(self)->list[dict]:...
 def execute_local(self,skill:str,params:dict,cancel)->dict:...
class DelegatedComputerControl:
 """Safe boundary: emits MCP delegation envelopes; does not pretend to execute input."""
 def __init__(self,server_name):self.server=server_name
 def envelope(self,operation,parameters,capability_id,expected):return {'mcp_server':self.server,'operation':operation,'parameters':parameters,'capability_id':capability_id,'expected_result':expected}
