import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import { platforms, listVMs } from '../discovery/platforms.js';
import { plan } from '../planner/planner.js';
import { Approval } from '../approval/engine.js';
import { Jobs } from '../jobs/manager.js';
import { waitPort } from '../guest/readiness.js';
const J = (x) => ({ content: [{ type: 'text', text: JSON.stringify(x, null, 2) }] });
const plans = new Map(), approval = new Approval(), jobs = new Jobs();
const op = { context: z.enum(['HOST', 'GUEST']), platform: z.enum(['virtualbox', 'hyperv', 'vmware', 'libvirt', 'wsl']), vm: z.string(), action: z.string(), parameters: z.record(z.unknown()).default({}), files: z.array(z.string()).default([]), resourceChanges: z.array(z.string()).default([]), persistentEffects: z.array(z.string()).default([]), potentialDataLoss: z.array(z.string()).default([]), risk: z.enum(['change', 'destructive', 'execute']) };
export async function createServer() { const s = new McpServer({ name: 'virtualization-master', version: '0.1.0' }); s.tool('list_virtualization_platforms', 'Discover verified host virtualization platforms.', {}, async () => J(platforms())); s.tool('list_vms', 'List VMs/distributions from available platforms.', {}, async () => J(listVMs())); s.tool('get_vm_info', 'Resolve exact VM without guessing.', { name: z.string(), platform: z.string().optional() }, async (a) => J(listVMs().filter(v => v.name === a.name && (!a.platform || v.platform === a.platform)))); s.tool('get_vm_capabilities', 'Return platform/VM capability and guest-control requirements.', { platform: z.string() }, async (a) => J(platforms().find(p => p.id === a.platform) ?? { state: 'NOT_DETECTED' })); s.tool('plan_operation', 'Plan exact HOST or GUEST argv and verification; no execution.', op, async (a) => { const p = plan(a, platforms()); plans.set(p.id, p); return J(p); }); s.tool('approve_operation', 'Issue exact expiring single-use approval token after explicit user approval.', { planId: z.string(), explicitApproval: z.string() }, async (a) => { const p = plans.get(a.planId); if (!p)
    throw Error('PLAN_NOT_FOUND'); return J(approval.issue(p, a.explicitApproval)); }); s.tool('execute_operation', 'Execute approved HOST/GUEST plan as job.', { planId: z.string(), approvalToken: z.string() }, async (a) => { const p = plans.get(a.planId); if (!p)
    throw Error('PLAN_NOT_FOUND'); approval.consume(p, a.approvalToken); return J(jobs.start(p)); }); s.tool('wait_for_vm', 'Wait for guest readiness via explicit SSH or WinRM TCP endpoint. VM powered-on state alone is insufficient.', { host: z.string(), port: z.number().int().min(1).max(65535), timeoutMs: z.number().int().min(1000).max(600000).default(120000) }, async (a) => J(await waitPort(a.host, a.port, a.timeoutMs))); s.tool('get_guest_capabilities', 'Report usable guest mechanisms from explicit connection data.', { vm: z.string(), platform: z.string(), host: z.string().optional(), ssh: z.boolean().default(false), winrm: z.boolean().default(false), guestAgent: z.boolean().default(false) }, async (a) => J({ context: 'GUEST', ...a, capabilities: { commands: a.ssh || a.winrm || a.guestAgent, files: a.ssh || a.winrm || a.guestAgent, packages: a.ssh || a.winrm || a.guestAgent }, note: 'Authentication and authorization must still succeed; guest agent presence does not imply arbitrary command support.' })); s.tool('detect_guest_package_manager', 'Run only after guest connection; returns safe detection argv candidates, not execution.', { os: z.enum(['linux', 'windows']) }, async (a) => J(a.os === 'linux' ? { candidates: ['apt-get', 'dnf', 'yum', 'pacman', 'zypper', 'apk'], probe: ['sh', '-lc', 'command -v apt-get || command -v dnf || command -v yum || command -v pacman || command -v zypper || command -v apk'] } : { candidates: ['winget', 'choco'], probe: ['powershell', '-NoProfile', '-Command', 'Get-Command winget,choco -ErrorAction SilentlyContinue | Select Name,Source'] })); s.tool('get_job', 'Get bounded output, exit code, context and status.', { jobId: z.string() }, async (a) => J(jobs.get(a.jobId))); s.tool('list_jobs', 'List current-process jobs.', {}, async () => J(jobs.list())); s.tool('cancel_job', 'Cancel running job after explicit literal confirmation.', { jobId: z.string(), explicitConfirmation: z.literal('CANCEL') }, async (a) => J(jobs.cancel(a.jobId))); s.tool('diagnose_virtualization', 'Classify failure by host/VM/guest layer.', { message: z.string() }, async (a) => J(diagnose(a.message))); return s; }
function diagnose(m) { for (const [r, code, next] of [[/not found|not recognized/i, 'PLATFORM_OR_COMMAND_NOT_FOUND', 'Run discovery'], [/access denied|permission/i, 'PERMISSION_DENIED', 'Check host/guest authorization; do not bypass'], [/connection refused|timeout/i, 'GUEST_NOT_READY', 'Check VM state, IP, network mode, SSH/WinRM/agent'], [/authentication|publickey|password/i, 'AUTHENTICATION_FAILED', 'Use authorized credential/key through configured mechanism'], [/no space/i, 'INSUFFICIENT_STORAGE', 'Inspect host and guest storage'], [/snapshot|checkpoint/i, 'SNAPSHOT_FAILED', 'Inspect state, disk type, guest agent/quiesce and snapshot tree']])
    if (r.test(m))
        return { code, cause: m, next, retry: false }; return { code: 'UNKNOWN_ERROR', cause: m, next: 'Identify HOST vs GUEST layer, VM state, readiness, mechanism, permission, disk and logs', retry: false }; }
export async function run() { const s = await createServer(); await s.connect(new StdioServerTransport()); }
//# sourceMappingURL=server.js.map