"""Taxonomy copied from Universal SDLC Generator (audiences, 21 phases, categories)."""

from __future__ import annotations

SDLC_PHASES = {
    "PHASE_01": {"name": "Inception & Vision", "short": "Vision", "icon": "💡", "description": "Define the 'Why'. Problem statement, goals, and success metrics.", "depth_low": "Simple Goal Statement", "depth_medium": "Vision Document & KPIs", "depth_high": "Strategic Alignment & ROI Analysis"},
    "PHASE_02": {"name": "Requirements Analysis", "short": "Reqs", "icon": "📋", "description": "Gather functional and non-functional requirements.", "depth_low": "User Stories / Feature List", "depth_medium": "SRS Document", "depth_high": "Formal Requirements Traceability Matrix"},
    "PHASE_03": {"name": "Feasibility & Risk", "short": "Risk", "icon": "⚖️", "description": "Technical, financial, and operational feasibility.", "depth_low": "Quick Tech Check", "depth_medium": "Risk Register", "depth_high": "Full Feasibility Study & Monte Carlo Simulation"},
    "PHASE_04": {"name": "System Architecture", "short": "Arch", "icon": "🏛️", "description": "High-level structure, patterns, and technology stack.", "depth_low": "Simple Diagram", "depth_medium": "C4 Model (Context/Container)", "depth_high": "Full C4 + ADRs + Sequence Diagrams"},
    "PHASE_05": {"name": "UI/UX & Interface", "short": "Design", "icon": "🎨", "description": "User experience, accessibility, and interface design.", "depth_low": "Basic Layout", "depth_medium": "Wireframes & Mockups", "depth_high": "Interactive Prototypes & Design System"},
    "PHASE_06": {"name": "Detailed Design", "short": "Detail", "icon": "🧩", "description": "Class diagrams, data models, and algorithms.", "depth_low": "Pseudocode", "depth_medium": "UML Class Diagrams", "depth_high": "Formal Specs & State Machines"},
    "PHASE_07": {"name": "Implementation (Core)", "short": "Code", "icon": "💻", "description": "Writing the actual source code.", "depth_low": "Scripting", "depth_medium": "Modular OOP/FP", "depth_high": "Clean Architecture / DDD"},
    "PHASE_08": {"name": "Data Persistence", "short": "Data", "icon": "💾", "description": "Database schema, storage, and retrieval.", "depth_low": "Flat Files / JSON", "depth_medium": "SQL/NoSQL Schema", "depth_high": "Distributed Data Store / Sharding"},
    "PHASE_09": {"name": "Integration", "short": "API", "icon": "🔗", "description": "Connecting modules, 3rd party APIs, and services.", "depth_low": "Direct Function Calls", "depth_medium": "REST/GraphQL APIs", "depth_high": "Event-Driven / Microservices Mesh"},
    "PHASE_10": {"name": "Security Implementation", "short": "Sec", "icon": "🔒", "description": "Auth, encryption, and vulnerability patching.", "depth_low": "Basic Password", "depth_medium": "OAuth2 / JWT / HTTPS", "depth_high": "Zero Trust / Pen Testing / Encryption at Rest"},
    "PHASE_11": {"name": "Configuration Mgmt", "short": "Config", "icon": "⚙️", "description": "Environment variables, feature flags, and settings.", "depth_low": "Hardcoded / .env", "depth_medium": "Config Files (YAML/JSON)", "depth_high": "Dynamic Config Service (Consul/etcd)"},
    "PHASE_12": {"name": "Quality Assurance", "short": "QA", "icon": "🧪", "description": "Testing strategy: Unit, Integration, E2E.", "depth_low": "Manual Testing", "depth_medium": "Unit + Integration Tests", "depth_high": "TDD / BDD / 90%+ Coverage / Chaos Eng"},
    "PHASE_13": {"name": "Build & Compilation", "short": "Build", "icon": "📦", "description": "Compiling source, managing artifacts.", "depth_low": "Direct Execution", "depth_medium": "Makefile / Gradle / Webpack", "depth_high": "Multi-stage Docker Builds / Bazel"},
    "PHASE_14": {"name": "DevOps & CI/CD", "short": "Ops", "icon": "🚀", "description": "Automation of testing and deployment pipelines.", "depth_low": "Manual Copy (FTP)", "depth_medium": "GitHub Actions / Jenkins", "depth_high": "GitOps / Progressive Delivery (Canary)"},
    "PHASE_15": {"name": "Observability", "short": "Logs", "icon": "📊", "description": "Logging, monitoring, tracing, and alerting.", "depth_low": "Print Statements", "depth_medium": "Centralized Logs (ELK)", "depth_high": "Full Observability (Metrics, Logs, Traces)"},
    "PHASE_16": {"name": "Performance Eng.", "short": "Perf", "icon": "⚡", "description": "Optimization, load testing, and profiling.", "depth_low": "None", "depth_medium": "Basic Profiling", "depth_high": "Load Testing (k6/JMeter) / Auto-scaling"},
    "PHASE_17": {"name": "User Acceptance (UAT)", "short": "UAT", "icon": "✅", "description": "Validation by end-users or stakeholders.", "depth_low": "Friend Check", "depth_medium": "Beta Testing Group", "depth_high": "Formal UAT Sign-off / Pilot Program"},
    "PHASE_18": {"name": "Documentation", "short": "Docs", "icon": "📚", "description": "User manuals, API docs, and code comments.", "depth_low": "README.md", "depth_medium": "Wiki / Sphinx / JSDoc", "depth_high": "Full Knowledge Base / Interactive Tutorials"},
    "PHASE_19": {"name": "Deployment", "short": "Release", "icon": "🌐", "description": "Releasing the software to production.", "depth_low": "Local Install", "depth_medium": "Cloud VM / Shared Hosting", "depth_high": "Kubernetes Cluster / Multi-Region CDN"},
    "PHASE_20": {"name": "Maintenance", "short": "Maint", "icon": "🔧", "description": "Bug fixes, updates, and technical debt.", "depth_low": "Ad-hoc Fixes", "depth_medium": "Sprint-based Support", "depth_high": "SRE / 24/7 On-call Rotation"},
    "PHASE_21": {"name": "Retirement / EOL", "short": "EOL", "icon": "🪦", "description": "Decommissioning the system and data archival.", "depth_low": "Delete Files", "depth_medium": "Data Backup & Uninstall", "depth_high": "Formal Sunset Plan & Data Migration"},
}

PROJECT_AUDIENCES = {
    "Kids (Age 6-12)": "LOW",
    "Teenagers (Age 13-17)": "LOW",
    "Students (College/Uni)": "MEDIUM",
    "Hobbyists & Makers": "MEDIUM",
    "Small Business Owners": "MEDIUM",
    "Corporate Employees": "HIGH",
    "Software Developers": "HIGH",
    "Data Scientists": "HIGH",
    "Researchers & Academics": "HIGH",
    "Government & Public Sector": "HIGH",
    "Healthcare Professionals": "HIGH",
    "Legal Professionals": "HIGH",
    "Financial Analysts": "HIGH",
    "Educators & Teachers": "MEDIUM",
    "Artists & Designers": "MEDIUM",
    "Gamers": "MEDIUM",
    "Parents": "LOW",
    "Seniors (Age 65+)": "LOW",
    "Non-Profits & NGOs": "MEDIUM",
    "Startups": "HIGH",
}

PROJECT_CATEGORIES = {
    "Web Development": {"complexity": "HIGH", "description": "Internet-based applications.", "items": ["Static Website", "Dynamic Web App", "E-commerce Platform", "Content Management System (CMS)", "Progressive Web App (PWA)", "Single Page Application (SPA)", "Serverless Web App", "Web Portal", "Forum / Community Site", "Blog Platform"]},
    "Mobile Development": {"complexity": "HIGH", "description": "Apps for smartphones and tablets.", "items": ["Native Android App", "Native iOS App", "Cross-Platform App (Flutter/React Native)", "Mobile Game", "Augmented Reality (AR) App", "Mobile Banking App", "Social Media App", "Utility App", "Health & Fitness Tracker", "Navigation / GPS App"]},
    "Desktop Software": {"complexity": "MEDIUM", "description": "Applications running on PC/Mac/Linux.", "items": ["Native Desktop App (Win/Mac/Linux)", "Cross-Platform Desktop (Electron/Qt)", "System Utility", "Text Editor / IDE", "Media Player", "File Manager", "Antivirus / Security Suite", "Office Suite (Word/Excel clone)", "Accounting Software", "CAD Software"]},
    "Game Development": {"complexity": "HIGH", "description": "Interactive entertainment.", "items": ["2D Platformer", "3D Open World", "First Person Shooter (FPS)", "Role Playing Game (RPG)", "Real Time Strategy (RTS)", "Puzzle Game", "Simulation Game", "Card Game", "Educational Game", "VR Game"]},
    "Data Science & AI": {"complexity": "HIGH", "description": "Intelligence and analysis.", "items": ["Machine Learning Model", "Deep Learning Neural Net", "Natural Language Processing (NLP) Tool", "Computer Vision System", "Recommendation Engine", "Chatbot / Conversational AI", "Data Visualization Dashboard", "Predictive Analytics Tool", "Big Data Pipeline", "ETL Process"]},
    "Systems & OS": {"complexity": "HIGH", "description": "Low-level computing.", "items": ["Operating System Kernel", "Device Driver", "Firmware / BIOS", "Bootloader", "File System", "Network Protocol Stack", "Virtual Machine Monitor (Hypervisor)", "Shell / Command Line Interpreter", "Compiler / Interpreter", "Embedded RTOS"]},
    "Cloud & DevOps": {"complexity": "HIGH", "description": "Infrastructure and operations.", "items": ["Cloud Infrastructure (IaaS)", "Container Orchestration (K8s)", "CI/CD Pipeline", "Monitoring & Observability Stack", "Serverless Function (FaaS)", "API Gateway", "Service Mesh", "Infrastructure as Code (Terraform)", "Log Aggregation System", "Secrets Management Vault"]},
    "Cybersecurity": {"complexity": "HIGH", "description": "Protection and defense.", "items": ["Firewall / IDS", "Penetration Testing Tool", "Encryption Software", "Password Manager", "VPN Client/Server", "SIEM System", "Vulnerability Scanner", "Forensic Analysis Tool", "Identity & Access Management (IAM)", "Secure Email Gateway"]},
    "Database Systems": {"complexity": "HIGH", "description": "Data storage engines.", "items": ["Relational Database Engine (SQL)", "NoSQL Document Store", "Graph Database", "Time-Series Database", "In-Memory Cache (Redis-like)", "Search Engine (Elasticsearch-like)", "Data Warehouse", "Blockchain Ledger", "Vector Database", "Embedded Database"]},
    "IoT & Embedded": {"complexity": "MEDIUM", "description": "Hardware and sensors.", "items": ["Home Automation Hub", "Wearable Device Firmware", "Industrial Sensor Network", "Smart Agriculture System", "Drone Control Software", "Robotics Controller", "Smart Vehicle System", "Medical Device Firmware", "Smart Grid Controller", "Environmental Monitor"]},
    "Enterprise Software": {"complexity": "HIGH", "description": "Business operations.", "items": ["ERP System", "CRM Software", "Supply Chain Management", "HR Management System (HRMS)", "Business Intelligence (BI) Tool", "Enterprise Service Bus (ESB)", "Document Management System", "IT Service Management (ITSM)", "Procurement System", "Asset Management"]},
    "Scientific Computing": {"complexity": "HIGH", "description": "Research and simulation.", "items": ["Physics Simulation", "Chemical Modeling", "Bioinformatics Pipeline", "Astronomical Data Processor", "Climate Model", "Mathematical Solver", "Finite Element Analysis (FEA)", "Computational Fluid Dynamics (CFD)", "Statistical Analysis Package", "Lab Information Management (LIMS)"]},
    "Multimedia": {"complexity": "MEDIUM", "description": "Audio, video, and graphics.", "items": ["Video Editor", "Audio Workstation (DAW)", "Image Editor (Photoshop-like)", "3D Modeling Tool", "Animation Software", "Streaming Server", "Codec Implementation", "Photo Organizer", "Screen Recorder", "MIDI Sequencer"]},
    "Networking": {"complexity": "HIGH", "description": "Connectivity and protocols.", "items": ["Router Firmware", "Network Switch OS", "Load Balancer", "Proxy Server", "DNS Server", "DHCP Server", "VoIP System", "CDN Node", "P2P Network Protocol", "Mesh Network Manager"]},
    "Education": {"complexity": "MEDIUM", "description": "Learning and teaching.", "items": ["Learning Management System (LMS)", "Student Information System", "Interactive Whiteboard Software", "Flashcard App", "Language Learning Platform", "Virtual Lab Simulator", "Plagiarism Checker", "Online Examination System", "Educational Game Engine", "Tutoring Marketplace"]},
    "Finance & FinTech": {"complexity": "HIGH", "description": "Money and markets.", "items": ["Core Banking System", "Payment Gateway", "Cryptocurrency Exchange", "Robo-Advisor", "High-Frequency Trading Bot", "Insurance Policy Engine", "Credit Scoring Model", "Personal Budgeting App", "Invoice Generator", "Tax Preparation Software"]},
    "Healthcare": {"complexity": "HIGH", "description": "Medical and wellness.", "items": ["Electronic Health Record (EHR)", "Hospital Management System", "Telemedicine Platform", "Medical Imaging Software (PACS)", "Pharmacy Management", "Clinical Trial Manager", "Patient Portal", "Diagnostic Expert System", "Fitness API Aggregator", "Mental Health Chatbot"]},
    "Legal & Gov": {"complexity": "HIGH", "description": "Law and administration.", "items": ["Case Management System", "E-Filing Portal", "Legislative Tracking", "Voting System", "Public Records Database", "Contract Analysis AI", "Compliance Checker", "Patent Search Engine", "Immigration Portal", "Land Registry"]},
    "Utilities & Tools": {"complexity": "LOW", "description": "Everyday helpers.", "items": ["Calculator", "Unit Converter", "To-Do List", "Note Taking App", "Calendar / Scheduler", "Clipboard Manager", "Screenshot Tool", "PDF Reader/Editor", "Zip/Unzip Utility", "Password Generator"]},
    "Kids & Education": {"complexity": "LOW", "description": "Fun and learning for children.", "items": ["Typing Tutor", "Math Practice Game", "Storybook Creator", "Coloring Book App", "Simple Scratch-like Coder", "Alphabet Learner", "Puzzle Solver", "Virtual Pet", "Homework Helper", "Science Experiment Guide"]},
    "Hobby & Lifestyle": {"complexity": "LOW", "description": "Personal interests.", "items": ["Recipe Manager", "Workout Tracker", "Habit Tracker", "Garden Planner", "Stargazing App", "Bird Identifier", "Collectibles Inventory", "Travel Journal", "Meditation Timer", "Chess Clock"]},
    "Small Business": {"complexity": "MEDIUM", "description": "Local commerce.", "items": ["Point of Sale (POS)", "Inventory Tracker", "Appointment Booker", "Loyalty Card System", "Simple Invoicing", "Employee Shift Scheduler", "Local Delivery Tracker", "Menu Designer", "Customer Feedback Kiosk", "QR Code Menu"]},
}
